version: "3.8"

services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: $PWD/work
        target: /home/jovyan/work
    env_file:
      - ../.env
    environment:
      - JUPYTER_ENABLE_LAB=yes
